### PR TITLE
Implement ability to only Minify set file types

### PR DESCRIPTION
**Pull request by SavageCore**
Implements Issue #27

### CODE REVIEW

**Comment by SavageCore** [comment]
@tssajo Do you need to perform a version bump for this to be installable with package sync? I removed my local copy and reinstalled but did not get this functionality.

**Comment by tssajo** [comment]
@SavageCore  Yes, I do. But I am in the process of adding support for JSON file minification too. And I wanted to only bump the version after that was added too. Maybe I do a version bump now and add the JSON file minification later.

**Comment by tssajo** [comment]
@SavageCore I released version 1.2.0 of `Minify`. The functionality is included in that version.

**Comment by SavageCore** [comment]
@tssajo Brilliant, keep up the good work.

**Comment by tssajo** [comment]
@SavageCore Somehow a bug slipped in when we added this new feature, see https://github.com/tssajo/Minify/issues/31
So I must release 1.2.1 today. I already found the cause.

**Comment by tssajo** [comment]
@SavageCore That bug that caused https://github.com/tssajo/Minify/issues/31 was present in the code base even before I merged your patch. The bug got reported today, so I thought it had to do something with the last few features we added. But it was just a coincident. ;)

**Pull request merged**
