### PR TITLE
Fix for uglifyjs and cleancss

### LINKED ISSUE #56: CSS source maps contain absolute paths with extra slashes in sources object
Hello. I love this plugin. You've done awesome work!

I am having a small problem though. When I minify my CSS files, my source map's sources object looks like this:
{"version":3,"sources":["L:\\\path\\\to\\\file\\\file.css"],"names":[],"mappings":"..."}

I need the sources object to not contain the path.  Am I missing an option to prevent this from happening somewhere?

### PR DESCRIPTION
**Pull request by ashucg**
fixes #56 and #59

### CODE REVIEW

**Comment by tssajo** [comment]
@ashucg Thanks for the contribution! I only had time just to take a quick look at it and it is looking good. Except that the new cwd thingy (changing the working directory) is not supported in SublimeText 2 where SUBL_ASYNC is false...

Anyhow, I'll look into this in more detail in the next couple of days and then I'll merge it.

Thanks again for your work on this!

**Comment by ashucg** [comment]
@tssajo thanks for pointing it out, I have made some changes :)

**Comment by tssajo** [comment]
@ashucg Thanks!
I just merged these changes into master. I'll test these on the weekend and if everything looking good then I'll do a new release.

**Comment by MiguelRipoll23** [comment]
@ashucg thank you for the fix!

**Comment by maryjos** [comment]
Hey how about that release? It's been quite some time and I just ran into this bug.

**Comment by tssajo** [comment]
@maryjos I've been very busy with some other stuff. But I try to make a new release today. Thank you for the reminder! ;)

**Pull request merged**
